import { CDN_BASE } from '../../constants/cdn'

const BASE = `${CDN_BASE}/videos`

export const book1Day        = `${BASE}/book-1-day.mp4`
export const book1Night      = `${BASE}/book-1-night.mp4`
export const book2Day        = `${BASE}/book-2-day.mp4`
export const book2Night      = `${BASE}/book-2-night.mp4`
export const cafe1Day        = `${BASE}/cafe-1-day.mp4`
export const cafe1Night      = `${BASE}/cafe-1-night.mp4`
export const cafe1RainyDay   = `${BASE}/cafe-1-rainy-day.mp4`
export const cafe1RainyNight = `${BASE}/cafe-1-rainy-night.mp4`
export const cafe2Day        = `${BASE}/cafe-2-day.mp4`
export const cafe2Night      = `${BASE}/cafe-2-night.mp4`
export const cafe2RainyDay   = `${BASE}/cafe-2-rainy-day.mp4`
export const cafe2RainyNight = `${BASE}/cafe-2-rainy-night.mp4`
export const chill1Day       = `${BASE}/chill-1-day.mp4`
export const chill1Night     = `${BASE}/chill-1-night.mp4`
export const chill1RainyDay  = `${BASE}/chill-1-rainy-day.mp4`
export const chill1RainyNight = `${BASE}/chill-1-rainy-night.mp4`
export const chill2Day       = `${BASE}/chill-2-day.mp4`
export const chill2Night     = `${BASE}/chill-2-night.mp4`
export const chill2RainyDay  = `${BASE}/chill-2-rainy-day.mp4`
export const chill2RainyNight = `${BASE}/chill-2-rainy-night.mp4`
export const desk1           = `${BASE}/desk-1.mp4`
export const desk2           = `${BASE}/desk-2.mp4`
export const desk3           = `${BASE}/desk-3.mp4`
export const forest1         = `${BASE}/forest-1.mp4`
export const forest2         = `${BASE}/forest-2.mp4`
export const northern1       = `${BASE}/northern-1.mp4`
export const northern2       = `${BASE}/northern-2.mp4`
export const ocean1          = `${BASE}/ocean-1.mp4`
export const ocean2          = `${BASE}/ocean-2.mp4`
export const spring1Day      = `${BASE}/spring-1-day.mp4`
export const spring1Night    = `${BASE}/spring-1-night.mp4`
export const spring2Day      = `${BASE}/spring-2-day.mp4`
export const spring2Night    = `${BASE}/spring-2-night.mp4`
export const summer1         = `${BASE}/summer-1.mp4`
export const summer2         = `${BASE}/summer-2.mp4`
export const van1            = `${BASE}/van-1.mp4`
export const van2            = `${BASE}/van-2.mp4`
