import { CDN_BASE } from '../cdn'
import type { BackgroundLink } from '../../types'

const BASE = `${CDN_BASE}/videos`

export const BACKGROUND_LINKS_LIST: BackgroundLink[] = [
  { set: 'chill', scene: 'scene1', day: true,  rainy: false, link: `${BASE}/chill-1-day.mp4` },
  { set: 'chill', scene: 'scene1', day: false, rainy: false, link: `${BASE}/chill-1-night.mp4` },
  { set: 'chill', scene: 'scene1', day: true,  rainy: true,  link: `${BASE}/chill-1-rainy-day.mp4` },
  { set: 'chill', scene: 'scene1', day: false, rainy: true,  link: `${BASE}/chill-1-rainy-night.mp4` },
  { set: 'chill', scene: 'scene2', day: true,  rainy: false, link: `${BASE}/chill-2-day.mp4` },
  { set: 'chill', scene: 'scene2', day: false, rainy: false, link: `${BASE}/chill-2-night.mp4` },
  { set: 'chill', scene: 'scene2', day: true,  rainy: true,  link: `${BASE}/chill-2-rainy-day.mp4` },
  { set: 'chill', scene: 'scene2', day: false, rainy: true,  link: `${BASE}/chill-2-rainy-night.mp4` },
  { set: 'northern', scene: 'scene1', day: true, rainy: false, link: `${BASE}/northern-1.mp4` },
  { set: 'northern', scene: 'scene2', day: true, rainy: false, link: `${BASE}/northern-2.mp4` },
  { set: 'desk', scene: 'scene1', day: true, rainy: false, link: `${BASE}/desk-1.mp4` },
  { set: 'desk', scene: 'scene2', day: true, rainy: false, link: `${BASE}/desk-2.mp4` },
  { set: 'desk', scene: 'scene3', day: true, rainy: false, link: `${BASE}/desk-3.mp4` },
  { set: 'forest', scene: 'scene1', day: true, rainy: false, link: `${BASE}/forest-1.mp4` },
  { set: 'forest', scene: 'scene2', day: true, rainy: false, link: `${BASE}/forest-2.mp4` },
  { set: 'ocean', scene: 'scene1', day: true, rainy: false, link: `${BASE}/ocean-1.mp4` },
  { set: 'ocean', scene: 'scene2', day: true, rainy: false, link: `${BASE}/ocean-2.mp4` },
  { set: 'cafe', scene: 'scene1', day: true,  rainy: false, link: `${BASE}/cafe-1-day.mp4` },
  { set: 'cafe', scene: 'scene1', day: false, rainy: false, link: `${BASE}/cafe-1-night.mp4` },
  { set: 'cafe', scene: 'scene1', day: true,  rainy: true,  link: `${BASE}/cafe-1-rainy-day.mp4` },
  { set: 'cafe', scene: 'scene1', day: false, rainy: true,  link: `${BASE}/cafe-1-rainy-night.mp4` },
  { set: 'cafe', scene: 'scene2', day: true,  rainy: false, link: `${BASE}/cafe-2-day.mp4` },
  { set: 'cafe', scene: 'scene2', day: false, rainy: false, link: `${BASE}/cafe-2-night.mp4` },
  { set: 'cafe', scene: 'scene2', day: true,  rainy: true,  link: `${BASE}/cafe-2-rainy-day.mp4` },
  { set: 'cafe', scene: 'scene2', day: false, rainy: true,  link: `${BASE}/cafe-2-rainy-night.mp4` },
  { set: 'van', scene: 'scene1', day: true, rainy: false, link: `${BASE}/van-1.mp4` },
  { set: 'van', scene: 'scene2', day: true, rainy: false, link: `${BASE}/van-2.mp4` },
  { set: 'summer', scene: 'scene1', day: true, rainy: false, link: `${BASE}/summer-1.mp4` },
  { set: 'summer', scene: 'scene2', day: true, rainy: false, link: `${BASE}/summer-2.mp4` },
  { set: 'spring', scene: 'scene1', day: true,  rainy: false, link: `${BASE}/spring-1-day.mp4` },
  { set: 'spring', scene: 'scene1', day: false, rainy: false, link: `${BASE}/spring-1-night.mp4` },
  { set: 'spring', scene: 'scene2', day: true,  rainy: false, link: `${BASE}/spring-2-day.mp4` },
  { set: 'spring', scene: 'scene2', day: false, rainy: false, link: `${BASE}/spring-2-night.mp4` },
  { set: 'book', scene: 'scene1', day: true,  rainy: false, link: `${BASE}/book-1-day.mp4` },
  { set: 'book', scene: 'scene1', day: false, rainy: false, link: `${BASE}/book-1-night.mp4` },
  { set: 'book', scene: 'scene2', day: true,  rainy: false, link: `${BASE}/book-2-day.mp4` },
  { set: 'book', scene: 'scene2', day: false, rainy: false, link: `${BASE}/book-2-night.mp4` },
]
