import {
  book1Day,
  book1Night,
  book2Day,
  book2Night,
  cafe1Day,
  cafe1Night,
  cafe1RainyDay,
  cafe1RainyNight,
  cafe2Day,
  cafe2Night,
  cafe2RainyDay,
  cafe2RainyNight,
  chill1Day,
  chill1Night,
  chill1RainyDay,
  chill1RainyNight,
  chill2Day,
  chill2Night,
  chill2RainyDay,
  chill2RainyNight,
  desk1,
  desk2,
  desk3,
  forest1,
  forest2,
  northern1,
  northern2,
  ocean1,
  ocean2,
  spring1Day,
  spring1Night,
  spring2Day,
  spring2Night,
  summer1,
  summer2,
  van1,
  van2,
} from '../../assets/videos'
import type { BackgroundLink } from '../../types'

export const BACKGROUND_LINKS_LIST: BackgroundLink[] = [
  { set: 'chill', scene: 'scene1', day: true, rainy: false, link: chill1Day },
  { set: 'chill', scene: 'scene1', day: false, rainy: false, link: chill1Night },
  { set: 'chill', scene: 'scene1', day: true, rainy: true, link: chill1RainyDay },
  { set: 'chill', scene: 'scene1', day: false, rainy: true, link: chill1RainyNight },
  { set: 'chill', scene: 'scene2', day: true, rainy: false, link: chill2Day },
  { set: 'chill', scene: 'scene2', day: false, rainy: false, link: chill2Night },
  { set: 'chill', scene: 'scene2', day: true, rainy: true, link: chill2RainyDay },
  { set: 'chill', scene: 'scene2', day: false, rainy: true, link: chill2RainyNight },
  { set: 'northern', scene: 'scene1', day: true, rainy: false, link: northern1 },
  { set: 'northern', scene: 'scene2', day: true, rainy: false, link: northern2 },
  { set: 'desk', scene: 'scene1', day: true, rainy: false, link: desk1 },
  { set: 'desk', scene: 'scene2', day: true, rainy: false, link: desk2 },
  { set: 'desk', scene: 'scene3', day: true, rainy: false, link: desk3 },
  { set: 'forest', scene: 'scene1', day: true, rainy: false, link: forest1 },
  { set: 'forest', scene: 'scene2', day: true, rainy: false, link: forest2 },
  { set: 'ocean', scene: 'scene1', day: true, rainy: false, link: ocean1 },
  { set: 'ocean', scene: 'scene2', day: true, rainy: false, link: ocean2 },
  { set: 'cafe', scene: 'scene1', day: true, rainy: false, link: cafe1Day },
  { set: 'cafe', scene: 'scene1', day: false, rainy: false, link: cafe1Night },
  { set: 'cafe', scene: 'scene1', day: true, rainy: true, link: cafe1RainyDay },
  { set: 'cafe', scene: 'scene1', day: false, rainy: true, link: cafe1RainyNight },
  { set: 'cafe', scene: 'scene2', day: true, rainy: false, link: cafe2Day },
  { set: 'cafe', scene: 'scene2', day: false, rainy: false, link: cafe2Night },
  { set: 'cafe', scene: 'scene2', day: true, rainy: true, link: cafe2RainyDay },
  { set: 'cafe', scene: 'scene2', day: false, rainy: true, link: cafe2RainyNight },
  { set: 'van', scene: 'scene1', day: true, rainy: false, link: van1 },
  { set: 'van', scene: 'scene2', day: true, rainy: false, link: van2 },
  { set: 'summer', scene: 'scene1', day: true, rainy: false, link: summer1 },
  { set: 'summer', scene: 'scene2', day: true, rainy: false, link: summer2 },
  { set: 'spring', scene: 'scene1', day: true, rainy: false, link: spring1Day },
  { set: 'spring', scene: 'scene1', day: false, rainy: false, link: spring1Night },
  { set: 'spring', scene: 'scene2', day: true, rainy: false, link: spring2Day },
  { set: 'spring', scene: 'scene2', day: false, rainy: false, link: spring2Night },
  { set: 'book', scene: 'scene1', day: true, rainy: false, link: book1Day },
  { set: 'book', scene: 'scene1', day: false, rainy: false, link: book1Night },
  { set: 'book', scene: 'scene2', day: true, rainy: false, link: book2Day },
  { set: 'book', scene: 'scene2', day: false, rainy: false, link: book2Night },
]
